"""Initial  Migration

Revision ID: c8b663ab00da
Revises: 89c4a26c290a
Create Date: 2022-05-19 15:31:20.044073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8b663ab00da'
down_revision = '89c4a26c290a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('Name', sa.String(length=50), nullable=False))
    op.drop_column('user', 'address')
    op.drop_column('user', 'firstName')
    op.drop_column('user', 'lastName')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lastName', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('firstName', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('address', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('user', 'Name')
    # ### end Alembic commands ###
